# (from: https://github.com/codecov/example-node/blob/master/.travis.yml)
language: node_js
sudo: false
node_js:
  - "9"
  - "8"
  - "7"
  - "6"
  - "5"
install:
  - npm install
script:
  - npm test
  # Build
  - npm run build
  # Test example
  - cd example && npm i && npm run example

